### ISSUE TITLE
Module "@angular/core" has no exported member "provide"

### ISSUE THREAD

**Issue by slavafomin** [fknop/angular-breakpoints#1]
Hello!

Thank you for this great module, it looks extremely useful.

However, I'm encountering the following error in Angular `4.2.5`:

`ERROR in ./node_modules/angular-breakpoints/index.ts (1,22): Module '"./node_modules/@angular/core/core"' has no exported member 'provide'.`

It looks like it's need to be updated in order to work with newer versions of Angular.

**Comment by fknop** [comment]
Hello!

Could you try with the new version? 

I'm not working with angular at the moment so I have a hard time keeping up with all the versions and keeping everything up to date!
